CREATE TABLE `USER` (
  `ID_USER` bigint(20) NOT NULL AUTO_INCREMENT,
  `EMAIl_ID` varchar(20) NOT NULL,
  `PASSWORD` varchar(20) NOT NULL,
  `CREATED_TIME` time DEFAULT NULL,
  `LAST_UPDATED_TIME` time DEFAULT NULL,
  PRIMARY KEY (`ID_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `NOTE` (
  `ID_NOTE` bigint(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(50) NOT NULL,
  `NOTE` varchar(1000) DEFAULT NULL,
  `CREATED_TIME` time DEFAULT NULL,
  `LAST_UPDATED_TIME` time DEFAULT NULL,
  `ID_USER` bigint(20) NOT NULL,
  PRIMARY KEY (`ID_NOTE`),
  KEY `ID_USER_FK` (`ID_USER`),
  CONSTRAINT `ID_USER_FK` FOREIGN KEY (`ID_USER`) REFERENCES `user` (`ID_USER`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO note_app_schema.USER
(EMAIl_ID, PASSWORD, CREATED_TIME, LAST_UPDATED_TIME) 
VALUES ('test1_user@yahoo.com', 'test1_user', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO note_app_schema.USER
(EMAIl_ID, PASSWORD, CREATED_TIME, LAST_UPDATED_TIME) 
VALUES ('test2_user@yahoo.com', 'test2_user',CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO note_app_schema.USER
(EMAIl_ID, PASSWORD, CREATED_TIME, LAST_UPDATED_TIME) 
VALUES ('test3_user@yahoo.com', 'test3_user',CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO note_app_schema.USER
(EMAIl_ID, PASSWORD, CREATED_TIME, LAST_UPDATED_TIME) 
VALUES ('test4_user@yahoo.com', 'test4_user', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO note_app_schema.USER
(EMAIl_ID, PASSWORD, CREATED_TIME, LAST_UPDATED_TIME) 
VALUES ('test5_user@yahoo.com', 'test5_user', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
commit;

